$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pf-cosmos-env
build:  
  path: .
inference_config:
  liveness_route:
    port: 8080
    path: /health
  readiness_route:
    port: 8080
    path: /health
  scoring_route:
    port: 8080
    path: /score 